//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int IdGame { get; set; }
        public string GameName { get; set; }
        public string GameJanr { get; set; }
        public string GameStoimost { get; set; }
        public string GameVipusk { get; set; }
        public string GameIsdatel { get; set; }
    }
}
