//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prochee
    {
        public int IdProchee { get; set; }
        public string NameProchhe { get; set; }
        public string TypeProchee { get; set; }
        public string PlatformProchee { get; set; }
        public string StoimostProchee { get; set; }
    }
}
