//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programm
    {
        public int IdProgramm { get; set; }
        public string ProgramName { get; set; }
        public string ProgramStoimost { get; set; }
    }
}
